Remove line importing python_2_unicode_compatible
Dear all,

Could you please fix that line? The function "python_2_unicode_compatible", which was part of "django.utils.encoding", seems to have been moved to "six". https://stackoverflow.com/a/43640425

The following error is thrown when Django tries to load actstream:
File "/usr/local/lib/python3.6/site-packages/actstream/models.py", line 7, in <module>
  from django.utils.encoding import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible'

Best regards,
Ricardo Rodriguez.